## 为何try里面放return，finally还会执行，理解其内部机制
* 不管有没有异常，finally中的代码都会执行
1. 先执行try中的语句，包括return后面的表达式
2. 有异常时,先执行catch中的语句，包括return后面的表达式,
3. 然后执行finally中的语句,如果finally里面有return语句，会提前退出，
4. 最后执行try中的return，有异常时执行catch中的return。

## JavaScript如何实现异步编程，可以详细描述EventLoop机制
1. 回调函数
2. 观察者模式
3. Promisese，async/await

mermaid
graph LR
    start[入口] -- 扫码 -- storeCode&tableNum --> conditionA{点餐首页}
    start[入口] -- 公众号菜单 -- storeCode --> conditionB{个人中心}
    conditionA --> stop[结束]
    conditionB --> stop