## 为何try里面放return，finally还会执行，理解其内部机制
* 不管有没有异常，finally中的代码都会执行
1. 先执行try中的语句，包括return后面的表达式
2. 有异常时,先执行catch中的语句，包括return后面的表达式,
3. 然后执行finally中的语句,如果finally里面有return语句，会提前退出，
4. 最后执行try中的return，有异常时执行catch中的return。

## JavaScript如何实现异步编程，可以详细描述EventLoop机制
1. 回调函数
2. 观察者模式
3. Promisese，async/await
* EventLoop机制: 同步执行 --> 微任务 --> 宏任务 --> 微任务 --> 宏任务 ···

## 宏任务和微任务分别有哪些
* 宏任务：包括整体代码script，setTimeout，setInterval
* 微任务：Promise，process.nextTick

## 使用Promise实现串行
* 每个任务推到数组里完成